name: uji_proyek_2
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

#------------ PACKAGES -----------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.1.0
  intl: ^0.19.0
  logger: ^2.0.2+1
  url_launcher: ^6.2.2
  # Icons
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  get_storage: ^2.1.1
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  iconsax: ^0.0.8

  #---------------------- ./ PACKAGES END ----------------#
dev_dependencies:
  flutter_test:
    sdk: flutter

  # State Management
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  #----------------------- LOCAL ASSETS ----------------#
  assets:
    - assets/images/user/
    - assets/logos/platform_image/
    - assets/icons/guitars/
    - assets/images/banner/
    - assets/images/product_sale/
    - assets/images/on_boarding_images/
  #----------------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets\fonts\Poppins-Medium.ttf
          weight: 500
        - asset: assets\fonts\Poppins-MediumItalic.ttf
          weight: 500
        - asset: assets\fonts\Poppins-SemiBold.ttf
          weight: 600
        - asset: assets\fonts\Poppins-Bold.ttf
          weight: 800
